### ISSUE TITLE
current design does not allow to trigger sibling test items simultaneously

### ISSUE THREAD

**Issue by rplevka** [reportportal/client-Python#34]
Looking into the code, the `ReportPortalService` class has a hardcoded mechanism of nesting the test items inside each other (it simply sequentially adds test items to `self.stack` which contains the uuids of the tests, and every action (start/finish item) is performed on the recent item).

This simply starts 1 test item inside another in case one triggers `start_test_item` several times in a row:
```
Launch
  |_ TestItem1
       |_ TestItem2
           |_ TestItem3
```
What I'm looking for is the ability to pass the uuid of the parent item as a parameter of the `start_test_item` (to use the `POST /{projectName}/item/{parentItem}` api endpoint) so I can trigger sibling items at various levels simultaneously, like:

```
Launch
  |_ TestItem1
  |    |_ TestItem1.1
  |    |   |_ TestItem1.1.1
  |    |   |_ TestItem1.1.2
  |    |_ TestItem1.2
  |_ TestItem2
       |_ TestItem2.1
       | _TestItem2.2
```

- this would also unblock the hierarchy feature for `pytest xdist`
- I don't know, whether there is a good reason for the current design

**Comment by krasoffski** [comment]
@DzmitryHumianiuk it seems like we need some docks related to RP API because I don't remember why this has such implementations. And which approach is used for Java.

**Comment by DzmitryHumianiuk** [comment]
@rplevka @krasoffski 
As I see, it just should be implemented in py agent, in order to be supported.

The only limitation we have is that you can report into Finished parent.
I mean, if your `TestItem1.1` already **finished**, and it has only `TestItem1.1.1` in it, then you can't simply add `TestItem1.1.2` into it.

It is a structure limitations.

posted issue: https://github.com/reportportal/reportportal/issues/490

**Comment by rplevka** [comment]
@DzmitryHumianiuk, thanks. Also, reporting to the finished item should update the attributes of this item (like finish time).
If your feature request gets implemented, the next step would be to rework the current stack-based design to a simple method call, where the method would accept a "parent_item" parameter

**Comment by DzmitryHumianiuk** [comment]
@rplevka agree

**Comment by rplevka** [comment]
@osherdp hey. I see you assigned this one to yourself. Have you had a chance to look into it?

**Comment by arozumenko** [comment]
@rplevka you can workaround it by manipulating self.stack list of service instance

**Comment by DzmitryHumianiuk** [comment]
@rplevka @arozumenko Folks, how about that issue?
Was it finally resolved?
Can we close it?

**Comment by DzmitryHumianiuk** [comment]
@rplevka @arozumenko Folks, how about that issue?
Was it finally resolved?
Can we close it?

**Comment by ndelon** [comment]
Hello,

I'd also like to give my feedback on this topic.

I'm writing a functional test framework named lemoncheesecake (http://lemoncheesecake.io - hub.com/lemoncheesecake/lemoncheesecake) that provides a built-in support for ReportPortal reporting and I encountered the exact same issue initially described by @rplevka .

About a year ago, I introduced parallelized tests support in lemoncheesecake, meaning that multiple tests could be executed at the same time and that result could be possibly pushed to ReportPortal for multiple tests at a time. This case is unfortunately not supported by reportportal_client and I had to limit ReportPortal support to sequential tests execution.

Some days ago, I released a new version 0.22.8 (https://github.com/lemoncheesecake/lemoncheesecake/blob/master/CHANGELOG.md#0228-2019-04-14 - https://github.com/lemoncheesecake/lemoncheesecake/commit/1595a4784e007f18bbde287a1b6a49d763175e4c) that workarounds this issue by pushing the whole test report at the very end of test execution when tests are run in parallel. When tests are run sequentially, test results are still pushed to ReportPortal in a "live" form.

Despite this workaround, I'm still interested by an improvement of reportportal_client to support pushing multiple test results in parallel so that "live" reporting can also work in a multi-threaded lemoncheesecake test execution. I can contribute on this if the ReportPortal team is willing to accept such a feature and contribution.

**Comment by DzmitryHumianiuk** [comment]
@ndelon @reportportal/python-contributors 
we don't have python engineer in team, and looking for contribution at this point

**Comment by ndelon** [comment]
Ok, then I'll trying to work on this. I'll keep you informed.

**Comment by DzmitryHumianiuk** [comment]
@rplevka @ndelon @reportportal/python-contributors 
**Ok Folks, good news here!**

ReportPortal v5 with endpoint `api/v2` will support fully async approach.

**In RPv4** Previously all reporting worked in a way that you send RQ to RP to create item, receive ID, and use certain server ID to populate structure on client side. This was the way to support hierarchy and blocked you from starting siblings and childs in "live" mode.

**in RPv5** async reporting will work in a way, that client side define `uuid` for any item, and build hierarchy at client side with client IDs. Without expecting response from server.
That means, that you can start your items, child and siblings at any moment, and push RQs in any sequence to server. 
Message Queue at server side will even accept StartRQ for child before Parent creation, if it will not find parent for correct `uuid` in db at this moment, it will send this RQ to special `retry-queue` and retry it in a few moments later.
This unblocks all possibilities for multi-threading of any kind.


We do re-work of java based client and agents right now.
And plan to prepare development guide, how it can be addressed in any other client/agent.

Before that moment, you can take a look into java implementation.
And play with `api/v2` endpoints in RPv5, even at beta instance.

@rplevka @ndelon feel free to start separate branch for v5 update, and start with implementation.
we will support you with answers.

**Comment by ndelon** [comment]
Thank you for your update @DzmitryHumianiuk . 

About the "id-is-controlled-by-the-client", I got the general idea even if I would need more time to figure out how it can be integrated into the Python client library.

I'll take a look at the Java implementation and i'll keep informed if I can spend time on this.

**Comment by DzmitryHumianiuk** [comment]
https://github.com/reportportal/documentation/blob/async-reporting/src/md/src/DevGuides/async-reporting.md#asynchronous-api

@ndelon please see detailed description on async reporting.
and reporting devguide itself

https://github.com/reportportal/documentation/blob/async-reporting/src/md/src/DevGuides/reporting.md

**Comment by ndelon** [comment]
Thanks for this update @DzmitryHumianiuk 

I'm interesting in contributing on this and I raised some questions about RPv5 - api/v2 on the #agent_python Slack channel to starting a discussion on this.

**Comment by HardNorth** [comment]
Please use `RPClient` class for multi-thread processing. And also pay attention that you need to create a fresh instance of the client for every new thread.
